# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # 📦 Aggiorna pacchetti gestiti da pnpm
  - package-ecosystem: "pnpm"
    directory: "/" # Dove si trova pnpm-lock.yaml
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "react"
        versions: ["18.x"] # Esempio: ignora aggiornamenti major

  # ⚙️ Aggiorna GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Dove si trovano i workflow
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 3

  # 🛡️ Controlli di sicurezza (abilitati implicitamente)
  # Dependabot segnala CVE e apre PR per fixare vulnerabilità critiche

